### ISSUE TITLE
Find nearest traffic light ahead of the vehicle

### ISSUE THREAD

**Issue by manu291** [Labonneguigue/CarND-Capstone-System-Integration#2]
That's step 1 of the two steps described in: [Traffic Light Detection Node](https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/462c933d-9f24-42d3-8bdc-a08a5fc866e4/concepts/d58e2c6a-1fd2-4e33-8912-861051ab301b)

**Comment by Labonneguigue** [comment]
Issue completed by #3
